"use client";

import { useEffect, useMemo, useState } from "react";

type Route = "home" | "store" | "cart" | "about" | "contact" | "login" | "register" | "welcome" | "panel";
type Product = { id:number; name:string; pet:"سگ"|"گربه"; brand:string; price:number; old?:number; tone:string; emoji:string };

const products: Product[] = [
  {id:1,name:"غذای خشک سگ رویال کنین Mini Adult",pet:"سگ",brand:"ROYAL CANIN",price:1950000,tone:"#f5f0e7",emoji:"🐕"},
  {id:2,name:"غذای خشک سگ پروپلن Adult Small Breed",pet:"سگ",brand:"PRO PLAN",price:2150000,old:2450000,tone:"#202b26",emoji:"🐶"},
  {id:3,name:"غذای خشک سگ مونژه Adult Dog",pet:"سگ",brand:"MONGE",price:1890000,tone:"#e8f1e7",emoji:"🦮"},
  {id:4,name:"غذای خشک سگ هیلز Science Plan",pet:"سگ",brand:"HILL'S",price:2210000,old:2600000,tone:"#f4efdf",emoji:"🐕‍🦺"},
  {id:5,name:"غذای خشک گربه رویال کنین Indoor",pet:"گربه",brand:"ROYAL CANIN",price:2090000,tone:"#faf2e8",emoji:"🐈"},
  {id:6,name:"غذای خشک گربه پروپلن Sterilised",pet:"گربه",brand:"PRO PLAN",price:2320000,old:2640000,tone:"#272e2a",emoji:"🐱"},
  {id:7,name:"غذای خشک گربه مونژه Adult Cat",pet:"گربه",brand:"MONGE",price:1740000,tone:"#f7ebef",emoji:"🐈‍⬛"},
  {id:8,name:"غذای خشک گربه هیلز Adult Chicken",pet:"گربه",brand:"HILL'S",price:2250000,tone:"#f8f0e4",emoji:"🐈"},
];

const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(n)+" تومان";

function Logo(){return <button className="logo" onClick={()=>go("home")}><img src="/petokio-logo.png" alt="پت اوکیو"/></button>}
function go(route:Route){location.hash=route==="home"?"":route}

function Header({route,count}:{route:Route,count:number}){
  return <header className="header shell">
    <Logo/>
    <nav aria-label="ناوبری اصلی">
      {[["home","صفحه اصلی"],["store","فروشگاه"],["about","درباره ما"],["contact","تماس با ما"]].map(([r,l])=><button key={r} className={route===r?"active":""} onClick={()=>go(r as Route)}>{l}</button>)}
    </nav>
    <div className="head-actions">
      <button className="icon-btn" aria-label="جستجو">⌕</button>
      <button className="icon-btn" aria-label="حساب کاربری" onClick={()=>go("login")}>♙</button>
      <button className="icon-btn cart-icon" aria-label="سبد خرید" onClick={()=>go("cart")}>🛒<b>{count}</b></button>
      <button className="consult" onClick={()=>go("contact")}>◉ مشاوره خرید</button>
    </div>
  </header>
}

function Footer(){return <><section className="trust shell">{[["▣","پرداخت امن","پرداخت آنلاین مطمئن"],["☊","مشاوره تخصصی","پاسخ‌گویی قبل و بعد خرید"],["▱","ارسال سریع","ارسال به سراسر کشور"],["♢","تضمین اصالت کالا","کالاهای اصل و معتبر"]].map(x=><div key={x[1]}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span></div>)}</section><footer><div className="shell footer-grid"><div><Logo/><p>پت‌اوکیو، همراه همیشگی شما برای تغذیه بهتر و حال خوب سگ‌ها و گربه‌های عزیزتان 🧡</p><div className="social">◉ ◉ ◉ ◉</div></div><div><h4>دسترسی سریع</h4><button onClick={()=>go("store")}>فروشگاه</button><button onClick={()=>go("about")}>درباره ما</button><button onClick={()=>go("contact")}>تماس با ما</button><button>مشاوره خرید</button></div><div><h4>راهنمای مشتری</h4><button>سؤالات متداول</button><button>روش‌های پرداخت</button><button>شرایط بازگشت کالا</button><button>حریم خصوصی</button></div><div><h4>نمادها و مجوزها</h4><div className="badges"><span>اعتماد<br/>الکترونیکی</span><span>ساماندهی</span><span>اتحادیه<br/>کشوری</span></div></div></div><div className="copyright">© تمامی حقوق این وب‌سایت متعلق به پت‌اوکیو است.</div></footer></>}

function PetArt({variant="hero"}:{variant?:string}){return <div className={`pet-art ${variant}`} role="img" aria-label="تصویرسازی سگ و گربه پت اوکیو"/>}

function ProductCard({p,onAdd}:{p:Product,onAdd:(p:Product)=>void}){return <article className="product-card"><button className="heart" aria-label="افزودن به علاقه‌مندی">♡</button>{p.old&&<span className="sale">٪{Math.round((1-p.price/p.old)*100)}</span>}<div className="pack" style={{background:p.tone}}><span>{p.emoji}</span><b>{p.brand}</b><small>PREMIUM PET FOOD</small></div><h3>{p.name}</h3><p>وزن ۲ کیلوگرم</p><div className="price">{money(p.price)} {p.old&&<del>{money(p.old)}</del>}</div><button className="orange" onClick={()=>onAdd(p)}>افزودن به سبد خرید 🛒</button></article>}

function Home({onAdd}:{onAdd:(p:Product)=>void}){return <>
  <main className="shell home">
    <section className="hero"><PetArt/><div className="hero-copy"><span className="eyebrow">پت شاد، خونه شاد 🐾</span><h1>حال خوب پت شما از<br/>تغذیه خوب شروع میشه</h1><p>غذای خوب، برند مطمئن و راهنمایی تخصصی برای پت شما</p><div className="hero-buttons"><button className="orange" onClick={()=>go("store")}>مشاهده فروشگاه 🛍</button><button className="outline" onClick={()=>go("contact")}>مشاوره خرید ☊</button></div><div className="micro-trust"><span>♢ تضمین اصالت کالا</span><span>▱ ارسال سریع</span><span>☊ مشاوره تخصصی</span></div></div></section>
    <section className="fast"><span>🛵</span><div><h2>تهران یا اطراف تهرانی؟</h2><p>هر چی بخوای یک ساعته به دستت می‌رسه!</p></div><i>⏱</i></section>
    <section className="pet-categories"><div className="dog"><span>🐶</span><h2>برای سگ‌ها</h2><button onClick={()=>go("store")}>مشاهده غذای سگ ←</button></div><div className="cat"><span>🐱</span><h2>برای گربه‌ها</h2><button onClick={()=>go("store")}>مشاهده غذای گربه ←</button></div></section>
    <div className="section-title"><h2>پرفروش‌ترین محصولات</h2><span>🐾</span></div><section className="product-row">{products.slice(0,5).map(p=><ProductCard key={p.id} p={p} onAdd={onAdd}/>)}</section>
    <section className="advisor"><div>🐶</div><span><h2>نمی‌دونی کدوم غذا برای پتت مناسبه؟</h2><p>متخصصین ما کمکت می‌کنن بهترین انتخاب رو براساس نژاد، سن و شرایط پتت داشته باشی.</p></span><button className="orange" onClick={()=>go("contact")}>دریافت مشاوره خرید ☊</button></section>
    <div className="section-title"><h2>برندهای محبوب</h2><span>♡</span></div><div className="brands">{["MONGE","Hill’s","PURINA PRO PLAN","ROYAL CANIN"].map(b=><b key={b}>{b}</b>)}</div>
  </main><Footer/></>}

function Store({onAdd}:{onAdd:(p:Product)=>void}){const [pet,setPet]=useState("همه"); const [q,setQ]=useState(""); const shown=products.filter(p=>(pet==="همه"||p.pet===pet)&&p.name.includes(q));return <><main className="shell store"><section className="store-hero"><PetArt variant="store-art"/><div><small>صفحه اصلی / فروشگاه</small><h1>فروشگاه پت‌اوکیو</h1><p>غذای باکیفیت برای سگ‌ها و گربه‌ها</p></div></section><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو در محصولات..."/><span>{shown.length} محصول</span><select><option>مرتب‌سازی: پرفروش‌ترین</option><option>ارزان‌ترین</option><option>گران‌ترین</option></select><button className="outline">فیلترها ☷</button></div><div className="store-layout"><aside><h3>🐾 دسته‌بندی</h3>{["همه","سگ","گربه"].map(x=><label key={x}><input type="radio" name="pet" checked={pet===x} onChange={()=>setPet(x)}/>{x==="همه"?"همه محصولات":"غذای "+x}</label>)}<hr/><h3>🐾 برند</h3>{["رویال کنین","هیلز","مونژه","پروپلن"].map(x=><label key={x}><input type="checkbox"/>{x}</label>)}<hr/><h3>🐾 بازه قیمت</h3><input type="range"/><div className="range"><span>۸۵۰,۰۰۰</span><span>۳,۵۰۰,۰۰۰</span></div><button className="green">اعمال فیلتر</button><button className="outline">حذف فیلترها</button></aside><section className="product-grid">{shown.map(p=><ProductCard key={p.id} p={p} onAdd={onAdd}/>)}</section></div><div className="pager"><button>بعدی</button><span>۴</span><span>۳</span><span>۲</span><b>۱</b><button>قبلی</button></div></main><Footer/></>}

function Cart({items,setItems}:{items:Product[],setItems:(x:Product[])=>void}){const total=items.reduce((s,p)=>s+p.price,0);return <><main className="shell cart-page"><div className="page-title"><small>صفحه اصلی / فروشگاه / سبد خرید</small><h1>سبد خرید شما 🐾</h1><p>محصولات انتخابی پت شما همین‌جاست</p></div><div className="cart-layout"><section className="cart-table">{items.length?items.map((p,i)=><article key={i}><div className="mini-pack" style={{background:p.tone}}>{p.emoji}</div><div><b>{p.name}</b><p>وزن ۲ کیلوگرم</p><em>حاوی پروتئین باکیفیت</em></div><strong>{money(p.price)}</strong><div className="qty"><button>+</button><span>۱</span><button>−</button></div><strong>{money(p.price)}</strong><button className="trash" onClick={()=>setItems(items.filter((_,j)=>j!==i))}>⌫</button></article>):<div className="empty"><span>🛒</span><h2>سبد خریدت خالیه</h2><button className="orange" onClick={()=>go("store")}>مشاهده فروشگاه</button></div>}</section><aside className="summary"><h2>خلاصه سفارش</h2><p><span>مجموع کالاها</span><b>{money(total)}</b></p><p className="discount"><span>تخفیف</span><b>۳۰۰,۰۰۰ تومان</b></p><p><span>هزینه ارسال</span><b className="green-text">رایگان</b></p><hr/><h3><span>مبلغ نهایی</span><b>{money(Math.max(0,total-300000))}</b></h3><label>کد تخفیف<input placeholder="کد تخفیف خود را وارد کنید"/></label><button className="orange">ادامه فرآیند خرید ←</button><button className="outline" onClick={()=>go("store")}>ادامه خرید</button></aside></div><section className="advisor"><div>🐶🐱</div><span><h2>برای انتخاب غذای مناسب پتت نیاز به راهنمایی داری؟</h2></span><button className="green" onClick={()=>go("contact")}>دریافت مشاوره خرید</button></section></main><Footer/></>}

function About(){const cards=[["♢","محصولات اورجینال","تمامی محصولات ما اصل و دارای اصالت کالا هستند."],["◆","قیمت‌گذاری مناسب","کیفیت بالا با قیمت منصفانه، همیشه در دسترس شما."],["♧","تیم متخصص و دامپزشک","تیم ما از متخصصان تغذیه و دامپزشکان تشکیل شده است."],["▣","بسته حمایتی","با هر خرید، یک بسته غذایی حمایتی ارسال می‌کنیم."],["◎","تنها واردکننده از فرانسه","محصولات منتخب و معتبر با کیفیت تضمین‌شده."]];return <><main className="shell about"><section className="about-hero"><PetArt/><div><h1>درباره پت‌اوکیو</h1><p>ما اینجاییم تا بهترین تغذیه و مراقبت را برای سگ‌ها و گربه‌های شما فراهم کنیم.</p><p>با محصولات باکیفیت، قیمت مناسب و راهنمایی تخصصی در کنار شما هستیم تا پت عزیزتان سالم‌تر و شادتر زندگی کند.</p></div></section><section className="value-grid">{cards.map(c=><article key={c[1]}><i>{c[0]}</i><h3>{c[1]}</h3><p>{c[2]}</p></article>)}</section><section className="about-split"><article><h2>تیم پت‌اوکیو 🐾</h2><p>تیم پت‌اوکیو از متخصصین تغذیه حیوانات و دامپزشکان تشکیل شده است.</p><div className="team">👨🏻‍⚕️ 👩🏻‍⚕️ 🐶 👨🏻‍💼 👩🏻‍💼</div></article><article><h2>چرا پت‌اوکیو؟ 🐾</h2><ul><li>انتخاب دقیق بهترین برندهای غذایی دنیا</li><li>مشاوره تخصصی تغذیه و سلامت توسط دامپزشک</li><li>پشتیبانی سریع و صمیمی در تمام مراحل خرید</li><li>تعهد واقعی به رفاه حیوانات و حمایت از جامعه</li></ul></article></section><section className="charity"><span>🎁</span><div><h2>بسته غذایی حمایتی برای حیوانات بی‌سرپرست</h2><p>با هر خرید شما، یک بسته غذایی حمایتی به صورت رایگان ارسال می‌شود.</p></div><button className="orange">درخواست ارسال رایگان ♥</button></section></main><Footer/></>}

function Contact(){const [sent,setSent]=useState(false);return <><main className="shell contact"><section className="contact-hero"><PetArt/><div><h1>تماس با ما</h1><p>ما اینجاییم تا به سوالات شما درباره سفارش، محصولات و مشاوره خرید پاسخ بدیم.</p></div><i>☎</i></section><section className="contact-cards">{[["☎","تلفن","۰۲۱-۲۲۳۴۵۶۷۸"],["✉","ایمیل","info@petokio.com"],["⌖","آدرس","تهران، خیابان شریعتی، پلاک ۱۲۴"],["◷","ساعات کاری","شنبه تا پنجشنبه، ۹ تا ۱۸"],["◎","ما را دنبال کنید","اینستاگرام · تلگرام · واتساپ"]].map(c=><article key={c[1]}><i>{c[0]}</i><h3>{c[1]}</h3><p>{c[2]}</p></article>)}</section><div className="contact-body"><section className="form-card"><h2>فرم ارسال پیام 🐾</h2><div className="form-grid"><label>نام<input placeholder="مثال: علی محمدی"/></label><label>شماره تماس<input placeholder="مثال: ۰۹۱۲ ۱۲۳ ۴۵۶۷"/></label></div><label>موضوع<select><option>انتخاب موضوع</option><option>مشاوره خرید</option><option>پیگیری سفارش</option></select></label><label>پیام<textarea placeholder="پیام خود را بنویسید..."/></label><button className="orange" onClick={()=>setSent(true)}>{sent?"پیام شما ارسال شد ✓":"ارسال پیام 🐾"}</button></section><aside><div className="consult-card"><span>🐶</span><h2>مشاوره خرید</h2><p>برای انتخاب بهترین غذای سگ یا گربه‌تان، تیم ما کنارته.</p><button className="green">درخواست مشاوره</button></div><div className="map">📍<button>مشاهده در نقشه</button></div></aside></div></main><Footer/></>}

function Auth({mode}:{mode:"login"|"register"}){const register=mode==="register";return <><main className="shell auth"><section className="auth-art"><PetArt/><div><h3>نیاز به راهنمایی دارید؟</h3><p>تیم پشتیبانی ما کنار شماست.</p><button className="green" onClick={()=>go("contact")}>دریافت مشاوره خرید</button></div></section><section className="auth-form"><h1>{register?"ثبت‌نام":"ورود"} 🐾</h1><p>{register?"برای ساخت حساب کاربری و خرید سریع‌تر، اطلاعات خود را وارد کنید.":"برای پیگیری سفارش و خرید سریع‌تر وارد حساب خود شوید."}</p>{register&&<label>نام و نام خانوادگی<input placeholder="مثال: علی احمدی"/></label>}<label>شماره موبایل<input placeholder="مثال: ۰۹۱۲ ۱۲۳ ۴۵۶۷"/></label><label>رمز عبور<input type="password" placeholder="رمز عبور خود را وارد کنید"/></label>{register&&<label>تکرار رمز عبور<input type="password" placeholder="رمز عبور را دوباره وارد کنید"/></label>}<div className="auth-options"><label><input type="checkbox"/> {register?"قوانین و حریم خصوصی را می‌پذیرم.":"مرا به خاطر بسپار"}</label>{!register&&<a>رمز عبور را فراموش کرده‌اید؟</a>}</div><button className="orange" onClick={()=>go(register?"welcome":"panel")}>{register?"ثبت‌نام":"ادامه"}</button><button className="outline">{register?"ثبت‌نام":"ورود"} با کد تایید</button><div className="or">یا</div><div className="social-auth"><button> Apple</button><button>G Google</button></div><p className="switch">{register?"حساب کاربری دارید؟":"حساب کاربری ندارید؟"} <button onClick={()=>go(register?"login":"register")}>{register?"ورود":"ثبت‌نام"}</button></p></section></main><Footer/></>}

function Welcome(){const [type,setType]=useState("سگ");return <main className="shell welcome"><Logo/><div className="steps">مرحله ۱ از ۳　 ● ─ ○ ─ ○</div><button className="back" onClick={()=>go("panel")}>← بازگشت</button><section className="welcome-grid"><div className="welcome-art"><h1>به خانواده پت‌اوکیو<br/>خوش اومدی!</h1><p>با تکمیل اطلاعات از پت‌اوکیو پیشنهادهای ویژه دریافت می‌کنی</p><PetArt/></div><div className="pet-form"><label>نام پت 🐾<input placeholder="مثال: نانی"/></label><label>نوع پت 🐾</label><div className="pet-choice"><button className={type==="سگ"?"selected":""} onClick={()=>setType("سگ")}>🐶 سگ</button><button className={type==="گربه"?"selected":""} onClick={()=>setType("گربه")}>🐱 گربه</button></div><label>تاریخ تولد 📅<input type="date"/></label><label>نژاد (اختیاری) 🐾<input placeholder="مثال: گلدن رتریور"/></label><button className="orange" onClick={()=>go("panel")}>ثبت پروفایل پت 🐾</button><button className="skip" onClick={()=>go("panel")}>فعلاً رد می‌کنم</button></div></section><section className="welcome-benefits"><article>🎁 <b>هدیه تولد پت</b><p>تخفیف و هدیه ویژه برای تولد پت شما</p></article><article>🏷️ <b>پیشنهادهای ویژه</b><p>تخفیف‌های مخصوص پت شما</p></article><article>🏅 <b>پیشنهاد مناسب سن و نژاد</b><p>پیشنهادهای تخصصی بر اساس اطلاعات پت</p></article></section></main>}

function Panel(){return <><main className="shell panel"><aside className="panel-nav"><button className="active">⌂ داشبورد</button>{["▣ سفارش‌های من","♙ پت‌های من","⌖ آدرس‌ها","♡ علاقه‌مندی‌ها","◇ کدهای تخفیف","♙ اطلاعات حساب","☊ پشتیبانی"].map(x=><button key={x}>{x}</button>)}<hr/><button className="logout" onClick={()=>go("home")}>خروج ↪</button></aside><section className="dashboard"><div className="hello"><PetArt/><div><h1>سلام، رضا 👋</h1><p>همه چیز برای مدیریت سفارش‌ها، آدرس‌ها و پت‌های دوست‌داشتنی‌ات اینجاست.</p><button className="orange">ویرایش اطلاعات</button> <button className="outline">مشاهده سفارش‌ها</button></div></div><div className="stats">{[["۲","سفارش‌های فعال","▣"],["۱","کد تخفیف فعال","◇"],["۳","پت‌های ثبت‌شده","🐾"],["۳,۴۵۰","امتیاز وفاداری","🏅"]].map(s=><article key={s[1]}><i>{s[2]}</i><span>{s[1]}<b>{s[0]}</b></span></article>)}</div><div className="dashboard-grid"><section><div className="section-title"><h2>پت‌های من 🐾</h2><button className="green" onClick={()=>go("welcome")}>+ افزودن پت جدید</button></div><div className="my-pets"><article><span>🐶</span><div><h3>لئو (سگ)</h3><p>نژاد گلدن رتریور</p><em>🎂 تولد نزدیکه</em></div></article><article><span>🐱</span><div><h3>میلو (گربه)</h3><p>پرشین</p><em>🎁 هدیه تولد فعال</em></div></article></div></section><aside className="birthday">🎁<h2>تاریخ تولد پت رو ثبت کن و روز تولدش تخفیف ویژه بگیر</h2><button className="green">ثبت و ویرایش تاریخ تولد</button></aside></div><div className="dashboard-grid lower"><section><h2>سفارش‌های اخیر</h2>{["PT-۱۴۰۳-۰۰۷۵۶","PT-۱۴۰۳-۰۰۷۱۲","PT-۱۴۰۳-۰۰۶۵۴"].map((x,i)=><div className="order" key={x}><b>{x}</b><span>{money([5870000,2340000,1960000][i])}</span><em>{["در حال ارسال","تحویل شده","آماده پردازش"][i]}</em><button>مشاهده جزئیات</button></div>)}</section><aside className="address"><h2>آدرس‌های من ⌖</h2><b>خانه</b><p>تهران، پاسداران، خیابان گل نبی، کوچه گلستان، پلاک ۱۲، واحد ۳</p><small>۰۹۱۲ ۱۲۳ ۴۵۶۷</small></aside></div></section></main><Footer/></>}

export default function App(){const [route,setRoute]=useState<Route>("home"); const [items,setItems]=useState<Product[]>(products.slice(0,3)); useEffect(()=>{const sync=()=>{const r=location.hash.slice(1) as Route; setRoute(r||"home")};sync();addEventListener("hashchange",sync);return()=>removeEventListener("hashchange",sync)},[]); const add=(p:Product)=>{setItems(x=>[...x,p]);}; const content=useMemo(()=>{switch(route){case"store":return <Store onAdd={add}/>;case"cart":return <Cart items={items} setItems={setItems}/>;case"about":return <About/>;case"contact":return <Contact/>;case"login":return <Auth mode="login"/>;case"register":return <Auth mode="register"/>;case"welcome":return <Welcome/>;case"panel":return <Panel/>;default:return <Home onAdd={add}/>}},[route,items]);return <div dir="rtl">{route!=="welcome"&&route!=="panel"&&<Header route={route} count={items.length}/>} {route==="panel"&&<Header route={route} count={items.length}/>} {content}<div className="toast" aria-live="polite">برای مشاهده صفحات از منوی بالا استفاده کنید</div></div>}
